buybackprogram/urls.py
from django.urls import path

from buybackprogram.views import calculate, common, programs, special_taxes, stats

app_name = "buybackprogram"

urlpatterns = [
    path("", common.index, name="index"),
    path("faq", common.faq, name="faq"),
    path("setup", programs.setup, name="setup"),
    path("program_add", programs.program_add, name="program_add"),
    path("location_add", programs.location_add, name="location_add"),
    path("user_settings_edit", common.user_settings_edit, name="user_settings_edit"),
    path(
        "location<int:location_pk>/remove",
        programs.location_remove,
        name="location_remove",
    ),
    path(
        "program/<int:program_pk>/leaderboard",
        stats.leaderboard,
        name="program_leaderboard",
    ),
    path(
        "program/<int:program_pk>/performance",
        stats.program_performance,
        name="program_performance",
    ),
    path(
        "program/<int:program_pk>/special_taxes",
        special_taxes.program_special_taxes,
        name="program_special_taxes",
    ),
    path(
        "program/<int:program_pk>/edit_item",
        special_taxes.program_edit_item,
        name="program_edit_item",
    ),
    path(
        "program/<int:program_pk>/edit_marketgroup",
        special_taxes.program_edit_marketgroup,
        name="program_edit_marketgroup",
    ),
    path(
        "program/<int:program_pk>/edit",
        programs.program_edit,
        name="program_edit",
    ),
    path(
        "program/<int:program_pk>/remove",
        programs.program_remove,
        name="program_remove",
    ),
    path(
        "program/<int:program_pk>/program_item/<int:item_pk>/remove",
        special_taxes.program_item_remove,
        name="program_item_remove",
    ),
    path(
        "program/<int:program_pk>/remove_all",
        special_taxes.program_item_remove_all,
        name="program_item_remove_all",
    ),
    path(
        "program/<int:program_pk>/calculate",
        calculate.program_calculate,
        name="program_calculate",
    ),
    path("my_stats", stats.my_stats, name="my_stats"),
    path(
        "tracking/<str:contract_title>/",
        stats.contract_details,
        name="contract_details",
    ),
    path("program_stats", stats.program_stats, name="program_stats"),
    path("program_stats_all", stats.program_stats_all, name="program_stats_all"),
    path(
        "item_autocomplete/",
        common.item_autocomplete,
        name="item_autocomplete",
    ),
    path(
        "solarsystem_autocomplete/",
        common.solarsystem_autocomplete,
        name="solarsystem_autocomplete",
    ),
    path(
        "marketgroup_autocomplete/",
        common.marketgroup_autocomplete,
        name="marketgroup_autocomplete",
    ),
]

buybackprogram/views/stats.py
import json
from datetime import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from django.shortcuts import render
from django.utils import timezone
from eveuniverse.models import EveEntity

from allianceauth.authentication.models import CharacterOwnership
from allianceauth.services.hooks import get_extension_logger

from buybackprogram.notes import (
    note_missing_from_contract,
    note_missing_from_tracking,
    note_quantity_missing_from_contract,
    note_quantity_missing_from_tracking,
)

from ..models import (
    Contract,
    ContractItem,
    ContractNotification,
    Tracking,
    TrackingItem,
)

logger = get_extension_logger(__name__)


@login_required
@permission_required("buybackprogram.basic_access")
def my_stats(request):

    # List for valid contracts to be displayed
    valid_contracts = []

    # Tracker values
    values = {
        "outstanding": 0,
        "finished": 0,
        "outstanding_count": 0,
        "finished_count": 0,
    }

    # Request user owned characters
    characters = CharacterOwnership.objects.filter(user=request.user).values_list(
        "character__character_id", flat=True
    )

    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(contract__isnull=False)
        .filter(contract__issuer_id__in=characters)
        .filter(contract__date_expired__gte=timezone.now())
        .prefetch_related("contract")
    )

    # Loop tracking objects to see if we have any contracts
    for tracking in tracking_numbers:

        # Get notes for this contract
        tracking.contract.notes = ContractNotification.objects.filter(
            contract=tracking.contract
        )

        # Walk the tracker values for contracts
        if tracking.contract.status == "outstanding":
            values["outstanding"] += tracking.contract.price
            values["outstanding_count"] += 1
        if tracking.contract.status == "finished":
            values["finished"] += tracking.contract.price
            values["finished_count"] += 1

        # Get the name for the issuer
        tracking.contract.issuer_name = EveEntity.objects.resolve_name(
            tracking.contract.issuer_id
        )

        # Get the name for the assignee
        tracking.contract.assignee_name = EveEntity.objects.resolve_name(
            tracking.contract.assignee_id
        )

        # Add contract to the valid contract list
        valid_contracts.append(tracking)

    context = {
        "contracts": valid_contracts,
        "values": values,
        "mine": True,
    }

    return render(request, "buybackprogram/stats.html", context)


@login_required
@permission_required("buybackprogram.basic_access")
def leaderboard(request, program_pk):
    # Tracker values
    monthstats = {
        "users": {},  # monthly stats per user
        "userinfo": {},  # profile information per user
        "months": None,  # all months
    }
    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(program_id=program_pk)
        .filter(contract__isnull=False)
        .prefetch_related("contract")
    )

    # Loop all tracking objects
    for tracking in tracking_numbers:
        # For finished contracts, gather more data
        if tracking.contract.status == "finished":
            month = datetime.strftime(tracking.contract.date_issued, "%Y-%m:%B %Y")
            if month not in monthstats["users"]:
                monthstats["users"][month] = {}  # User data per month

            # Collect ISK data per user
            user = tracking.contract.issuer_id
            if user not in monthstats["users"][month]:
                monthstats["users"][month][user] = [
                    0,  # contract total
                    0,  # donation total
                ]
            monthstats["users"][month][user][0] += tracking.contract.price
            monthstats["users"][month][user][1] += tracking.donation

            if user not in monthstats["userinfo"]:
                monthstats["userinfo"][user] = {
                    "name": EveEntity.objects.resolve_name(user),
                    "pic": f"https://images.evetech.net/characters/{user}/portrait?size=32",
                }

    monthstats["months"] = sorted(list(monthstats["users"].keys()))
    context = {
        "stats": json.dumps(monthstats),
    }

    return render(request, "buybackprogram/leaderboards.html", context)


@login_required
@permission_required("buybackprogram.manage_programs")
def program_performance(request, program_pk):
    firstbench = datetime.now()
    lastbench = datetime.now()
    # Tracker values
    monthstats = {
        "status": {},
        "overall": {"all": {}},
        "items": {},
        "categories": {},
        "donations": {"all": {}},
    }
    allmonths = set()

    # Category to Item mapping
    category2items = {}

    # Export data
    dumpdata = [
        [
            "Contract ID",
            "Date Issued",
            "Date Finished",
            "User ID",
            "Total ISK",
            "Object Cateogry",
            "Object ID",
            "Object Name",
            "Object Quant",
            "Object ISK",
        ]
    ]

    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(program_id=program_pk)
        .filter(contract__isnull=False)
        .prefetch_related("contract")
    )

    logger.debug(
        "Performance bench: %.2f" % (datetime.now() - lastbench).total_seconds()
    )
    lastbench = datetime.now()
    # Loop all tracking objects
    for tracking in tracking_numbers:
        month = datetime.strftime(tracking.contract.date_issued, "%Y-%m")
        allmonths.add(month)

        if month not in monthstats["status"]:
            monthstats["status"][
                month
            ] = {}  # status of all contracts issued during a given month

        # Gather stats on all contracts' statuses
        if tracking.contract.status not in monthstats["status"][month]:
            monthstats["status"][month][tracking.contract.status] = 0
        monthstats["status"][month][tracking.contract.status] += 1

        # For finished contracts, gather more data
        if tracking.contract.status == "finished":
            # "overall": {"all": {"isk": {}, "q": {}, }
            if month not in monthstats["overall"]["all"]:
                monthstats["overall"]["all"][month] = [0, 0]  # isk, q
                monthstats["donations"]["all"][month] = [0, 0]  # isk, q

            monthstats["overall"]["all"][month][0] += tracking.contract.price
            monthstats["overall"]["all"][month][1] += 1

            monthstats["donations"]["all"][month][0] += tracking.donation
            if tracking.donation > 0:
                monthstats["donations"]["all"][month][1] += 1

            logger.debug(
                "Performance loop bench: %.2f"
                % (datetime.now() - lastbench).total_seconds()
            )
            lastbench = datetime.now()
            # Collect ISK data per items
            tracking_items = TrackingItem.objects.filter(tracking=tracking)
            for item in tracking_items:
                if item.eve_type.name not in monthstats["items"]:
                    monthstats["items"][item.eve_type.name] = {}
                if month not in monthstats["items"][item.eve_type.name]:
                    monthstats["items"][item.eve_type.name][month] = [0, 0]
                monthstats["items"][item.eve_type.name][month][0] += item.buy_value
                monthstats["items"][item.eve_type.name][month][1] += item.quantity
                # cache[tracking.contract.issuer_id] = EveEntity.objects.resolve_name(tracking.contract.issuer_id)

                # Collect item category data
                catid = item.eve_type.eve_group.name
                if catid not in category2items:
                    category2items[catid] = set()
                category2items[catid].add(item.eve_type.name)

                if catid not in monthstats["categories"]:
                    monthstats["categories"][catid] = {}
                if month not in monthstats["categories"][catid]:
                    monthstats["categories"][catid][month] = [0, 0]
                monthstats["categories"][catid][month][0] += item.buy_value
                monthstats["categories"][catid][month][1] += item.quantity

                # Collect data for export
                dumpdata.append(
                    [
                        tracking.id,
                        datetime.strftime(
                            tracking.contract.date_issued, "%Y-%m-%d %H:%M:%S"
                        ),
                        datetime.strftime(
                            tracking.contract.date_completed, "%Y-%m-%d %H:%M:%S"
                        ),
                        tracking.contract.issuer_id,
                        tracking.contract.price,
                        item.eve_type.eve_group.name,
                        item.eve_type.id,
                        item.eve_type.name,
                        item.quantity,
                        item.buy_value,
                    ]
                )

    logger.debug(
        "Performance exit loop bench: %.2f"
        % (datetime.now() - lastbench).total_seconds()
    )
    lastbench = datetime.now()
    # Reformat data so that it is easier to use billboard.js
    allmonths = sorted(list(allmonths))

    scaling = {}
    hscaling = {}
    for strata in ("overall", "items", "categories", "donations"):
        scaling[strata] = []
        for yi in monthstats[strata].keys():
            scaling[strata] += [
                monthstats[strata][yi][x][0] for x in monthstats[strata][yi].keys()
            ]
        if len(scaling[strata]) == 0:

buybackprogram/templates/buybackprogram/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    {% if NIGHT_MODE %}
        <link rel="stylesheet" type="text/css" href="{% static 'buybackprogram/css/style_dark.css' %}">
        {% else %}
        <link rel="stylesheet" type="text/css" href="{% static 'buybackprogram/css/style_light.css' %}">
    {% endif %}
{% endblock extra_css %}

{% block page_title %}{% translate "buybackprogram" %}{% endblock %}

{% block content %}
    <div class="allianceauth-buyback-program-plugin">
        <div class="col-lg-12 container">
            <h1 class="page-header text-center">{% translate "Buyback Program" %}</h1>
            {% include 'buybackprogram/menu.html' %}
            {% block details %}{% endblock %}
        </div>
    </div>
{% endblock %}

buybackprogram/templates/buybackprogram/contract_details.html
{% extends 'buybackprogram/base.html' %}
{% load i18n %}
{% load humanize %}
{% load price_formats %}
{% load static %}
{% block details %}
<div class="panel-body" style="min-height: 100px;">
    <div>
    {% for note in notes %}
        <div>
            <i style="color:{{note.color}}" class="fas {{note.icon}}"> {{note.message}}</i>
        </div>
    {% endfor %}
    </div>

    <div class="table-responsive">
        <h4>Contract information:</h4>
        <table style="width: 50%" class="tabletable-condensed">
            <tbody>
                <tr>
                    <th >{% trans "Date issued" %}</th>
                    <td>{{contract.date_issued}}</td>
                </tr>
                <tr>
                    <th >{% trans "Issued from" %}</th>
                    <td>{{contract.issuer_name}}</td>
                </tr>
                <tr>
                    <th >{% trans "Issued to" %}</th>
                    <td>{{contract.assignee_name}}</td>
                </tr>
                <tr>
                    <th >{% trans "Time pending" %}</th>
                    <td>{{contract.date_issued|timesince }}</td>
                </tr>
                <tr>
                    <th >{% trans "Status" %}</th>
                    <td>{{contract.status}}</td>
                </tr>
                <tr>
                    <th >{% trans "Tracking #" %}</th>
                    <td>{{contract.title}}</td>
                </tr>
                <tr>
                    <th >{% trans "Asking price" %}</th>
                    <td>{{contract.price|floatformat:0|intcomma}} ISK</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="table-responsive" style="margin: 20px 0;">
       <div>
            <h4>{% trans "Accepted Location(s)" %}</h4>
            <table id="contract" style="margin: 20px auto;" class="table table-striped table-condensed">
            {% for location in tracking.program.location.all %}
                <tr>
                    <td>
                        <div>{{location.location_display_name}}</div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        </div>
        <div style="margin: 20px 0;">
            <h4>{% trans "Invoice" %}</h4>
            <table id="contract" style="margin: 20px auto;" class="table table-striped table-condensed">
                <tr>
                    <th>Price before expenses</th>
                    <td>{{tracking.value|floatformat:0|intcomma}} ISK</td>
                </tr>
                <tr>
                    <th>Program taxes</th>
                  <td>{{tracking.taxes|floatformat:0|intcomma}} ISK</td>
                </tr>
                <tr>
                    <th>Hauling cost</th>
                    <td>{{tracking.hauling_cost|floatformat:0|intcomma}} ISK</td>
                </tr>
                <tr>
                    <th>Donation amount</th>
                    <td>{{tracking.donation|floatformat:0|intcomma}} ISK <i></i></td>
                </tr>
                <tr>
                    <th style="border-top:2px dotted black;">Net price</th>
                    {% if tracking.net_price >= 0 %}
                        <td style="border-top:2px dotted black;">{{tracking.net_price|floatformat:0|intcomma }} ISK</td>
                    {% else %}
                        <td style="border-top:2px dotted black;">0 ISK <i><s>{{tracking.net_price|floatformat:0|intcomma }} ISK</s></i><td>
                    {% endif %}
                </tr>

            </table>
        </div>
    </div>

    <div class="table-responsive">
        <h4>{% trans "Invoiced items (original calculation)" %}</h4>
        <table class="table table-striped table-condensed">
            <thead>
                <tr>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Quantity" %}</th>
                    <th>{% trans "Buy value" %}</th>
                    <th>{% trans "Note" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for item in tracking_items %}
                        <tr>
                            <td><img class="item-icon" src="https://image.eveonline.com/Type/{{item.eve_type.id}}_64.png" />{{item.eve_type.name}}</td>
                            <td>{{item.quantity|intcomma}}</td>
                            <td>{{item.buy_value|floatformat:0|intcomma}} ISK</td>
                            <td>
                                {% for note in item.notes %}
                                    <i style="color: {{note.color}};" class="fas {{note.icon}}" title="{{note.message}}"></i>
                                {% endfor %}
                            </td>
                        </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    <div class="table-responsive">
        <h4>{% trans "Contract contains (actual contract)" %}</h4>
        <table class="table table-striped table-condensed">
            <thead>
                <tr>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Quantity" %}</th>
                    <th>{% trans "Note" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for item in contract_items %}
                        <tr>
                            <td><img class="item-icon" src="https://image.eveonline.com/Type/{{item.eve_type.id}}_64.png" />{{item.eve_type.name}}</td>
                            <td>{{item.quantity|intcomma}}</td>
                            <td>
                                {% for note in item.notes %}
                                    <i style="color: {{note.color}};" class="fas {{note.icon}}" title="{{note.message}}"></i>
                                {% endfor %}
                            </td>
                        </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div>
        <a class="btn btn-warning btn-sm" href="{% url 'buybackprogram:my_stats' %}">
                                <i class="fas fa-arrow-left">Back to my stats</i>
        </a>
    </div>
</div>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% if NIGHT_MODE %}
        <link rel="stylesheet" type="text/css" href="{% static 'buybackprogram/css/style_dark.css' %}">
        {% else %}
        <link rel="stylesheet" type="text/css" href="{% static 'buybackprogram/css/style_light.css' %}">
    {% endif %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/location_add.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="panel-heading">
  <h3 class="panel-title">Buyback locations</h3>
</div>
<div class="panel-body" style="min-height: 100px;">
  <div>
    <form class="form" action="{% url 'buybackprogram:location_add' %}" method="POST">
      {% csrf_token %}
      {{ form|bootstrap }}
      <button type="submit" class="btn btn-primary">Add location</button>
    </form>
  </div>
  <div class="table-responsive" style="margin: 20px 0;">
    <table id="locations" style="margin: 20px auto;" class="table table-striped table-condensed">
      <thead>
        <th>Solar System</th>
        <th style="text-align: center;">Name</th>
        <th style="text-align: center;">Structure ID</th>
      </thead>
      <tbody>
        {% for location in locations %}
          {% if location.owner.user == request.user %}
            <tr>
              <td>{{location.eve_solar_system.name}}</td>
              <td style="text-align: center;">{{location.name}}</td>
              <td style="text-align: center;">{{location.structure_id}}</td>
              <td><a class="btn btn-sm btn-danger" href="{% url 'buybackprogram:location_remove' location_pk=location.id %}">Delete</a></td>
            </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybackprogram/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybackprogram/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-buybackprogram-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'buybackprogram:index' %}">{% trans "Buyback Programs" %}</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-buybackprogram-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'buybackprogram:faq' %}">
                    <a href="{% url 'buybackprogram:faq' %}">
                        FAQ
                    </a>
                </li>
                <li class="{% navactive request 'buybackprogram:my_stats' %}">
                    <a href="{% url 'buybackprogram:my_stats' %}">
                        My Statistics
                    </a>
                </li>
                {% if perms.buybackprogram.manage_programs %}
                    <li class="{% navactive request 'buybackprogram:program_stats' %}">
                        <a href="{% url 'buybackprogram:program_stats' %}">
                            My Program Statistics
                        </a>
                    </li>
                {% endif %}
                {% if perms.buybackprogram.see_all_statics %}
                    <li class="{% navactive request 'buybackprogram:program_stats_all' %}">
                        <a href="{% url 'buybackprogram:program_stats_all' %}">
                            All Program Statistics
                        </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if perms.buybackprogram.manage_programs %}
                    <a class="btn btn-default navbar-btn" href="{% url 'buybackprogram:setup' %}">
                        1. Setup Manager
                    </a>
                    <a class="btn btn-default navbar-btn" href="{% url 'buybackprogram:location_add' %}">
                        2. Add/edit location
                    </a>
                    <a class="btn btn-default navbar-btn" href="{% url 'buybackprogram:program_add' %}">
                        3. Create Program
                    </a>
                {% endif %}

                <a class="btn btn-default navbar-btn" href="{% url 'buybackprogram:user_settings_edit' %}">My Settings</a>
            </ul>
        </div>
    </div>
</nav>

buybackprogram/templates/buybackprogram/program_edit.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="panel-heading">
  <h3 class="panel-title">Edit program</h3>
</div>
<div class="panel-body" style="min-height: 100px;">
  <form class="form" action="{% url 'buybackprogram:program_edit' program_pk=program.id %}" method="POST">
    {% csrf_token %}
    {{ form|bootstrap }}
    <button type="submit" class="btn btn-primary">Edit Program</button>
  </form>
  {% endblock %}


  {% block extra_javascript %}
  <script type="text/javascript" src="{% static 'buybackprogram/js/bootstrap-autocomplete.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'buybackprogram/js/autocomplete.js' %}"></script>
</div>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/program_edit_item.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="panel-heading">
  <h3 class="panel-title">Program Special Taxes</h3>
</div>
<div class="panel-body" style="min-height: 100px;">
  {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
  <div>
    <form class="form" action="{% url 'buybackprogram:program_edit_item' program_pk=program.id %}" method="POST">
      {% csrf_token %}
      {{ form|bootstrap }}
      <button type="submit" class="btn btn-primary">Add item</button>
    </form>
    <a class="btn btn-default navbar-btn btn-warning" href="{% url 'buybackprogram:program_special_taxes' program_pk=program.id %}"><i class="fas fa-long-arrow-alt-left">Item taxes</i></a>
  </div>
  {% endif %}

</div>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybackprogram/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybackprogram/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/program_edit_marketgroup.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="panel-heading">
  <h3 class="panel-title">Program Special Taxes</h3>
</div>
<div class="panel-body" style="min-height: 100px;">
  {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
  <div>
    <form class="form" action="{% url 'buybackprogram:program_edit_marketgroup' program_pk=program.id %}" method="POST">
      {% csrf_token %}
      {{ form|bootstrap }}
      <button type="submit" class="btn btn-primary">Add items</button>
    </form>
    <a class="btn btn-default navbar-btn btn-warning" href="{% url 'buybackprogram:program_special_taxes' program_pk=program.id %}"><i class="fas fa-long-arrow-alt-left">Item taxes</i></a>
  </div>
  {% endif %}

</div>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybackprogram/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybackprogram/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/program_special_taxes.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="panel-heading">
  <h3 class="panel-title">Program Special Taxes</h3>
</div>
<div class="panel-body" style="min-height: 100px;">
  {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
    <a class="btn btn-sm btn-warning" href="{% url 'buybackprogram:program_edit_item' program_pk=program.id %}"><i class="fas fa-plus">Add item</i></a>
    <a class="btn btn-sm btn-warning" href="{% url 'buybackprogram:program_edit_marketgroup' program_pk=program.id %}"><i class="fas fa-plus">Add market group</i></a>
    <a class="btn btn-sm btn-danger" href="{% url 'buybackprogram:program_item_remove_all' program_pk=program.id %}"><i class="fas fa-trash">Deleta all items</i></a>
  {% endif %}
  <div class="table-responsive" style="margin: 20px 0;">
    <table id="program_items" style="margin: 20px auto;" class="table table-striped table-condensed">
      <thead>
        <th>Name</th>
        <th style="text-align: center;">Tax adjustment</th>
        <th style="text-align: center;">Total tax</th>
        <th style="text-align: center;">Is allowed</th>
        {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
          <th style="text-align: center;">Actions</th>
        {% endif %}
      </thead>
      <tbody>
        {% for item in program_items %}
          <tr>
            <td>{{item.item_type.name}}</td>
            <td style="text-align: center;">{{item.item_tax}} %</td>
            <td style="text-align: center;">{{item.item_tax|add:program.tax }} %</td>
            {% if not item.disallow_item %}
               <td style="text-align: center;"><i class="fas fa-check" style="color:green;"></i></td>
            {% else %}
              <td style="text-align: center;"><i class="fas fa-times" style="color:red;"></i></td>
            {% endif %}
            {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
              <td style="text-align: center;">
                <a class="btn btn-danger btn-sm" href="{% url 'buybackprogram:program_item_remove' item_pk=item.item_type.id program_pk=program.id %}">Delete</a>

              </td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybackprogram/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybackprogram/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/user_settings.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="panel-heading">
  <h3 class="panel-title">Buyback user settings</h3>
</div>
<div class="panel-body" style="min-height: 100px;">
  <div>
    <form class="form" action="{% url 'buybackprogram:user_settings_edit' %}" method="POST">
      {% csrf_token %}
      {{ form|bootstrap }}
      <button type="submit" class="btn btn-primary">Update Settings</button>
    </form>
  </div>
</div>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}